### ISSUE TITLE
Watson Developer Handbook Handbook wrong URL/Missing

### ISSUE THREAD

**Issue by haythamelkhoja** [dtoczala/watson-landing-page#1]
The address embedded for **Watson Developer Handbook** is wrong: https://ibm.ent.box.com/file/51752480029

**Comment by dtoczala** [comment]
That link -> https://ibm.ent.box.com/file/51752480029 works for me, but I am inside of IBM.  Let me see if the visibility isn't set correctly in Box.
Looking into this.

**Comment by dtoczala** [comment]
The correct link is https://ibm.box.com/s/nav52vt6q2xwib5zqwupwjf78mxtgems
I have fixed the link in the main page.
